### ISSUE TITLE
Reference error: $ is not defined

### ISSUE THREAD

**Issue by system-failure-b8xy** [Mrcomputer1/ScratchXto3#5]
When converting the ScratchX Mesh extension (https://technoboy10.github.io/mesh/), I get this error:"

evalmachine.<anonymous>:4
    $.ajax({
    ^

ReferenceError: $ is not defined
    at evalmachine.<anonymous>:4:5
    at evalmachine.<anonymous>:58:3
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6)
    at module.exports (C:\MyStuff\ScratchXto3\run.js:140:5)
    at C:\MyStuff\ScratchXto3\wizard.js:35:7
    at Interface._onLine (node:readline:485:5)
    at Interface._line (node:readline:864:8)
    at Interface._ttyWrite (node:readline:1216:14)
    at ReadStream.onkeypress (node:readline:288:10)
    "
    Btw, I did not make this extension, so if it is a problem with the converter, please fix it.
    
    Sincerely,
    JustinsKittens

**Comment by Mrcomputer1** [comment]
I haven't really been maintaining this converter (I made it years ago and have since forgotten most of how it works 😛). But the error you are getting is because the converter doesn't support extensions that use jQuery and only really supports basic extensions.

**Comment by system-failure-b8xy** [comment]
Ok, thanks, have a nice day!
